POST http://localhost:3000/api/v1/items HTTP/1.1
Content-Type: application/json

{
    "uid": "P000008",
    "code": "sjQ23408K",
    "description": "Weird stuff",
    "short_description": "must",
    "upc_code": "6523540947122",
    "model_number": "63-OFFTq0T",
    "commodity_code": "oTo304",
    "item_line": 11,
    "item_group": 73,
    "item_type": 14,
    "unit_purchase_quantity": 47,
    "unit_order_quantity": 13,
    "pack_order_quantity": 11,
    "supplier_id": 34,
    "supplier_code": "SUP423",
    "supplier_part_number": "E-86805-uTM",
    "created_at": "",
    "updated_at": ""
}

###
GET http://localhost:3000/api/v1/items HTTP/1.1

###

GET http://localhost:3000/api/v1/items/P000009 HTTP/1.1

###

GET http://localhost:3000/api/v1/items/P000001/totals HTTP/1.1
###

GET http://localhost:3000/api/v1/items/P000003/storage HTTP/1.1

###


DELETE http://localhost:3000/api/v1/items/P000005 HTTP/1.1

###

PUT http://localhost:3000/api/v1/items HTTP/1.1
content-type: application/json

{
    "uid": "P000001",
    "code": "sjQ23408K",
    "description": "Hazy flower",
    "short_description": "must",
    "upc_code": "6523540947122",
    "model_number": "63-OFFTq0T",
    "commodity_code": "oTo304",
    "item_line": 11,
    "item_group": 73,
    "item_type": 14,
    "unit_purchase_quantity": 47,
    "unit_order_quantity": 13,
    "pack_order_quantity": 11,
    "supplier_id": 34,
    "supplier_code": "SUP423",
    "supplier_part_number": "E-86805-uTM",
    "created_at": "",
    "updated_at": ""
}