GET http://localhost:3000/api/v1/item_lines HTTP/1.1


###

GET http://localhost:3000/api/v1/item_lines/1 HTTP/1.1


###

GET http://localhost:3000/api/v1/item_lines/1/items HTTP/1.1


###

PUT http://localhost:3000/api/v1/item_lines/2 HTTP/1.1
Content-Type: application/json

{
    "id": 2,
    "name": "Fashion",
    "description": "",
    "created_at": "1990-01-04 22:40:49",
    "updated_at": "2003-05-17 08:21:43"
}