GET http://localhost:3000/api/v1/shipments HTTP/1.1

###

GET http://localhost:3000/api/v1/shipments/1 HTTP/1.1

###

GET http://localhost:3000/api/v1/shipments/1/items HTTP/1.1

###

GET http://localhost:3000/api/v1/shipments/1/orders HTTP/1.1

###