GET http://localhost:3000/api/v2/inventories HTTP/1.1
API_KEY: a1b2c3d4e5
// or API_KEY: f6g7h8i9j0
###

GET http://localhost:3000/api/v2/inventories/1 HTTP/1.1
API_KEY: a1b2c3d4e5
// or API_KEY: f6g7h8i9j0
###

POST http://localhost:3000/api/v2/inventories HTTP/1.1
API_KEY: a1b2c3d4e5
Content-Type: application/json

{
    "id": 10,
    "item_id": "P000001",
    "description": "Face-to-face clear-thinking complexity",
    "item_reference": "sjQ23408K",
    "locations": [
        1,
        2,
        3,
        4,
        5
    ],
    "total_on_hand": 262,
    "total_expected": 0,
    "total_ordered": 80,
    "total_allocated": 41,
    "total_available": 141,
    "created_at": "",
    "updated_at": ""
}
###

PUT http://localhost:3000/api/v2/inventories/1 HTTP/1.1
API_KEY: a1b2c3d4e5
Content-Type: application/json

{
    "id": 1,
    "item_id": "P000001",
    "description": "Face-to-face clear-thinking complexity",
    "item_reference": "sjQ23408K",
    "locations": [
        1,
        2,
        3,
        4,
        5
    ],
    "total_on_hand": 262,
    "total_expected": 0,
    "total_ordered": 80,
    "total_allocated": 41,
    "total_available": 141,
    "created_at": "",
    "updated_at": ""
}
###

DELETE http://localhost:3000/api/v2/inventories/1 HTTP/1.1
API_KEY: a1b2c3d4e5
###