// a = admin, f = client

GET http://localhost:3000/api/v2/shipments HTTP/1.1
API_KEY: a1b2c3d4e5
//API_KEY: f6g7h8i9j0

###

GET http://localhost:3000/api/v2/shipments/1 HTTP/1.1
API_KEY: a1b2c3d4e5
//API_KEY: f6g7h8i9j0

###

GET http://localhost:3000/api/v2/shipments/1/items HTTP/1.1
API_KEY: a1b2c3d4e5
//API_KEY: f6g7h8i9j0
###

GET http://localhost:3000/api/v2/shipments/1/orders HTTP/1.1
API_KEY: a1b2c3d4e5
//API_KEY: f6g7h8i9j0
###

POST http://localhost:3000/api/v2/shipments HTTP/1.1
API_KEY: a1b2c3d4e5
//API_KEY: f6g7h8i9j0
Content-Type: application/json

{
    "id": 12,
    "order_id": 14,
    "source_id": 50,
    "order_date": "2025-02-03",
    "request_date": "2024-10-19",
    "shipment_date": "2025-01-12",
    "shipment_type": "S",
    "shipment_status": "Pending",
    "notes": "",
    "carrier_code": "PostNL",
    "carrier_description": "",
    "service_code": "Fastest",
    "payment_type": "Manual",
    "transfer_mode": "Ground",
    "total_package_count": 31,
    "total_package_weight": 594.42,
    "created_at": "",
    "updated_at": "",
    "items": [
        {
            "item_id": "P000001",
            "amount": 5
        }
    ]
}

###

DELETE http://localhost:3000/api/v2/shipments/1 HTTP/1.1
API_KEY: a1b2c3d4e5
//API_KEY: f6g7h8i9j0

###

PUT http://localhost:3000/api/v2/shipments/1 HTTP/1.1
API_KEY: a1b2c3d4e5
//API_KEY: f6g7h8i9j0
Content-Type: application/json

{
    "id": 1,
    "order_id": 1,
    "source_id": 50,
    "order_date": "2025-02-03",
    "request_date": "2024-10-19",
    "shipment_date": "2025-01-12",
    "shipment_type": "S",
    "shipment_status": "Pending",
    "notes": "",
    "carrier_code": "PostNL",
    "carrier_description": "",
    "service_code": "Fastest",
    "payment_type": "Manual",
    "transfer_mode": "Ground",
    "total_package_count": 31,
    "total_package_weight": 594.42,
    "created_at": "",
    "updated_at": "",
    "items": []
}

###

PUT http://localhost:3000/api/v2/shipments/1/commit HTTP/1.1
API_KEY: a1b2c3d4e5
Content-Type: application/json

###

// Add items to a shipment
PUT http://localhost:3000/api/v2/shipments/1/items HTTP/1.1
API_KEY: a1b2c3d4e5
//API_KEY: f6g7h8i9j0
Content-Type: application/json 

[
    {
        "item_id": "P000001",
        "amount": 16233
    }
]

###

PUT http://localhost:3000/api/v2/shipments/1/orders HTTP/1.1
API_KEY: a1b2c3d4e5
//API_KEY: f6g7h8i9j0
Content-Type: application/json

[1, 2, 3]

###

PATCH http://localhost:3000/api/v2/shipments/1 HTTP/1.1
API_KEY: a1b2c3d4e5
//API_KEY: f6g7h8i9j0
Content-Type: application/json

{
    "order_id": 11,
    "source_id": 502132,
    "transfer_mode": "Ground",
    "total_package_count": 3131,
    "total_package_weight": 59234.42,
    "items": [
            {
                "item_id": "P123132132132132131",
                "amount": 16233
            }
        ]
}
###

PATCH http://localhost:3000/api/v2/shipments/1/items HTTP/1.1
API_KEY: a1b2c3d4e5
//API_KEY: f6g7h8i9j0
Content-Type: application/json

{
    "item_id": "P000001",
    "amount": 1
}