GET http://localhost:3000/api/v1/item_groups HTTP/1.1
API_KEY: a1b2c3d4e5
// or API_KEY: f6g7h8i9j0
###

GET http://localhost:3000/api/v1/item_groups/1 HTTP/1.1
API_KEY: a1b2c3d4e5
// or API_KEY: f6g7h8i9j0
###


GET http://localhost:3000/api/v1/item_groups/73/items HTTP/1.1
API_KEY: a1b2c3d4e5
// or API_KEY: f6g7h8i9j0
###

POST http://localhost:3000/api/v1/item_groups HTTP/1.1
API_KEY: a1b2c3d4e5
Content-Type: application/json

{
    "id": 10,
    "name": "BBBB",
    "description": "",
    "created_at": "",
    "updated_at": ""
}
###

PUT http://localhost:3000/api/v1/item_groups/1 HTTP/1.1
API_KEY: a1b2c3d4e5
Content-Type: application/json

{
    "id": 1,
    "name": "AAAAAA",
    "description": "",
    "created_at": "",
    "updated_at": ""
}
###

DELETE http://localhost:3000/api/v1/item_groups/5 HTTP/1.1
API_KEY: a1b2c3d4e5
###