name: Run Unit Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - run: npm ci
    - run: npm test

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install xmllint
      run: sudo apt-get update && sudo apt-get install -y libxml2-utils

    - name: Restore dependencies for UnitTests
      run: dotnet restore ./Tests/V2/UnitTests/UnitTests.csproj

    - name: Build UnitTests project
      run: dotnet build ./Tests/V2/UnitTests/UnitTests.csproj --configuration Release

    - name: Run Unit Tests and generate a test result report
      run: dotnet test ./Tests/V2/UnitTests/UnitTests.csproj --no-build --configuration Release --logger:"trx;LogFileName=test-results.trx"

    - name: Display Test Report in Summary
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: JEST Tests
        path: '**/test-results.trx'
        reporter: jest-junit
  
    - name: Upload Test Results as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/test-results.trx'