name: Run Unit Tests with Test Summary

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies for UnitTests
      run: dotnet restore ./Tests/V2/UnitTests/UnitTests.csproj

    - name: Build UnitTests project
      run: dotnet build ./Tests/V2/UnitTests/UnitTests.csproj --configuration Release

    - name: Run Unit Tests and generate a test result report
      run: dotnet test ./Tests/V2/UnitTests/UnitTests.csproj --no-build --configuration Release --logger:"trx;LogFileName=test-results.trx"

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Unit Tests Summary
        path: '**/test-results.trx'
        reporter: junit

    - name: Upload Test Results as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/test-results.trx'
