name: Run Unit Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies for UnitTests
      run: dotnet restore ./Tests/V2/UnitTests/UnitTests.csproj

    - name: Build UnitTests project
      run: dotnet build ./Tests/V2/UnitTests/UnitTests.csproj --configuration Release

    - name: Run Unit Tests and generate a test result report
      run: dotnet test ./Tests/V2/UnitTests/UnitTests.csproj --no-build --configuration Release --logger:"trx;LogFileName=test-results.trx"

    - name: Display Test Results in Summary
      run: |
        # Convert the trx file to a human-readable format and display it in the GitHub summary
        if [ -f test-results.trx ]; then
          echo "## Test Results" >> $GITHUB_STEP_SUMMARY
          echo "### Test Run Summary" >> $GITHUB_STEP_SUMMARY
          # Extract test results from trx file and append to summary
          # We use 'trx2html' here to convert trx to HTML and append to the summary. Ensure the tool is installed in the environment.
          trx2html test-results.trx >> $GITHUB_STEP_SUMMARY
        else
          echo "No test results found." >> $GITHUB_STEP_SUMMARY
        fi

    - name: Upload Test Results as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/test-results.trx'
