name: Run Unit Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies for UnitTests
      run: dotnet restore ./Tests/V2/UnitTests/UnitTests.csproj

    - name: Build UnitTests project
      run: dotnet build ./Tests/V2/UnitTests/UnitTests.csproj --configuration Release

    - name: Run Unit Tests and generate a test result report
      run: dotnet test ./Tests/V2/UnitTests/UnitTests.csproj --no-build --configuration Release --logger:"trx;LogFileName=test-results.trx"

    - name: Install xmllint (or trx2html if required)
      run: sudo apt-get update && sudo apt-get install -y libxml2-utils

    - name: Display Test Results in Summary
      run: |
        # Check if the trx file exists in the correct directory
        if [ -f Tests/V2/UnitTests/TestResults/test-results.trx ]; then
          echo "## Test Results" >> $GITHUB_STEP_SUMMARY
          echo "### Test Run Summary" >> $GITHUB_STEP_SUMMARY
          # Using 'dotnet' command to extract summary info instead of xmllint
          dotnet tool install --global dotnet-reportgenerator-globaltool
          reportgenerator "-reports:Tests/V2/UnitTests/TestResults/test-results.trx" "-targetdir:coverage-report"
          cat coverage-report/index.htm >> $GITHUB_STEP_SUMMARY
        else
          echo "No test results found." >> $GITHUB_STEP_SUMMARY
        fi
    

    - name: Upload Test Results as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/test-results.trx'
